//this is an iojs script to recreate the timesheet table in the database in postgres
var pg = require('pg');
var config = require('../config.json');
var conString = "pg://postgres:postgres@localhost:5432/employees";

var client = new pg.Client(conString);
client.connect();
console.log(2);
client.query("DROP TABLE IF EXISTS Timesheets");
// Creat table and insert 2 records into it

try {
    client.query(
       "CREATE TABLE IF NOT EXISTS Timesheets ( index serial PRIMARY KEY, timesheet_id INT, user_foreignkey INT , service_description varchar(32) , service_duration REAL, engagement_number INT )"
    );
} catch (error) {
    console.error("this is an error", error);
}

setTimeout(function(){
    client.end();
    console.log("Success");
}, 1000);
/* Data Structure
{
    "timesheet_id": "probably some UUID number",
    "user_foreignkey": "foreign key ID for user, should that be DB generated or generated by the application?",
    "service_duration": "duration of service",
    "service_description": "description of service",
    "engagement_number": "foreign key ID of customer"
}
*/
